/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;
import javax.swing.*;
import java.awt.*;
/**
 *
 * @author Samantha
 */
    public class BlockCard extends javax.swing.JPanel {
    private int blockNumber;
    private boolean occupied;
    private String fileName;
    private Color blockColor;
    /**
     * Creates new form BlockCard
     */
    public BlockCard(int blockNumber) {
        
        this.blockNumber = blockNumber;
        this.occupied = false;
        this.fileName = "";
        this.blockColor = Color.LIGHT_GRAY;
        
        setPreferredSize(new Dimension(40, 40));
        setBackground(blockColor);
        setBorder(BorderFactory.createLineBorder(Color.DARK_GRAY));
        setLayout(new BorderLayout());
        
        JLabel label = new JLabel(String.valueOf(blockNumber), SwingConstants.CENTER);
        label.setFont(new Font("Arial", Font.PLAIN, 10));
        add(label, BorderLayout.CENTER);
    }
    
    public void setOccupied(boolean occupied, String fileName, Color color) {
        this.occupied = occupied;
        this.fileName = fileName;
        this.blockColor = color;
        
        
        if (occupied) {
            setBackground(color);
            removeAll();
            String labelText = "<html><center><b>" + fileName + "</b><br>" + blockNumber + "</center></html>";
            JLabel label = new JLabel(labelText, SwingConstants.CENTER);
            label.setFont(new Font("Arial", Font.PLAIN, 12));
            add(label, BorderLayout.CENTER);
            //setToolTipText("Bloque " + blockNumber + " - Archivo: " + fileName);
        } else {
            setBackground(Color.LIGHT_GRAY);
            removeAll();
            JLabel label = new JLabel(String.valueOf(blockNumber), SwingConstants.CENTER);
        label.setFont(new Font("Arial", Font.PLAIN, 10));
        label.setForeground(Color.BLACK);
        add(label, BorderLayout.CENTER);
            //setToolTipText("Bloque " + blockNumber + " - Libre");
        }
        repaint();
    }
    
    public boolean isOccupied() {
        return occupied;
    }
    
    public int getBlockNumber() {
        return blockNumber;
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
