/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import javax.swing.JOptionPane;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;
import model.Archivo;
import model.Directorio;
import model.FileSystemElement;
import model.SistemaArchivos;

/**
 *
 * @author Samantha
 */
public class MainWindow extends javax.swing.JFrame {
    private SistemaArchivos sistemaArchivos;
    private DefaultTreeModel treeModel;
    private DefaultMutableTreeNode rootNode;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainWindow.class.getName());

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        sistemaArchivos = new SistemaArchivos();
        InicializarArbol();
    }
    
    private void InicializarArbol(){
     // Crear el nodo raíz a partir del directorio raíz del sistema
        Directorio raiz = sistemaArchivos.getRaiz();
        rootNode = new DefaultMutableTreeNode(raiz);
        treeModel = new DefaultTreeModel(rootNode);
         jTree1.setModel(treeModel);
         jTree1.setCellRenderer(new CustomTreeRendered());
          jTree1.expandPath(new TreePath(rootNode.getPath()));

    }
    
    private DefaultMutableTreeNode getSelectedNode() {
    TreePath selectedPath = jTree1.getSelectionPath();
    if (selectedPath != null) {
        return (DefaultMutableTreeNode) selectedPath.getLastPathComponent();
    }
    return null;
}
private void agregarNodoAlArbol(DefaultMutableTreeNode parentTreeNode, Directorio directorio) {
    FileSystemElement nuevoElemento = directorio.buscarElemento(FileDirName.getText().trim());
    if (nuevoElemento != null) {
        DefaultMutableTreeNode nuevoNodo = new DefaultMutableTreeNode(nuevoElemento);
        treeModel.insertNodeInto(nuevoNodo, parentTreeNode, parentTreeNode.getChildCount());
        jTree1.scrollPathToVisible(new TreePath(nuevoNodo.getPath()));
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        isAdmin = new javax.swing.JRadioButton();
        IsAdmin = new javax.swing.JRadioButton();
        CreateFile = new javax.swing.JButton();
        CreateDir = new javax.swing.JButton();
        FileDirName = new javax.swing.JTextField();
        jSpinner1 = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(230, 612));

        jTree1.setBackground(new java.awt.Color(51, 51, 51));
        jTree1.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jTree1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(779, 260));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 779, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 204));
        jPanel5.setPreferredSize(new java.awt.Dimension(270, 372));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("CRUD");

        isAdmin.setForeground(new java.awt.Color(51, 51, 51));
        isAdmin.setText("User");
        isAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isAdminActionPerformed(evt);
            }
        });

        IsAdmin.setForeground(new java.awt.Color(51, 51, 51));
        IsAdmin.setText("Admin");
        IsAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IsAdminActionPerformed(evt);
            }
        });

        CreateFile.setText("Crear Archivo");
        CreateFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateFileActionPerformed(evt);
            }
        });

        CreateDir.setText("Crear Directorio");
        CreateDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateDirActionPerformed(evt);
            }
        });

        FileDirName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileDirNameActionPerformed(evt);
            }
        });

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(CreateDir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(CreateFile)
                .addGap(20, 20, 20))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(isAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(IsAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(FileDirName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isAdmin)
                    .addComponent(IsAdmin))
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FileDirName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateFile)
                    .addComponent(CreateDir))
                .addContainerGap(201, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel5, java.awt.BorderLayout.LINE_END);

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void isAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isAdminActionPerformed

    private void IsAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IsAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IsAdminActionPerformed

    private void CreateFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateFileActionPerformed

    private void CreateDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateDirActionPerformed
        // TODO add your handling code here:
        String nombre = FileDirName.getText().trim();
        if (nombre.isEmpty()){
            JOptionPane.showMessageDialog(this, "Ingrese un nombre para el directorio");
            return;
        }
         // Obtener el nodo seleccionado
        DefaultMutableTreeNode selectedNode = getSelectedNode();
        Directorio directorioPadre;
   
        
        
         if (selectedNode==null) {
            directorioPadre = sistemaArchivos.getRaiz();
            selectedNode = rootNode;
        }else{
             Object userObject = selectedNode.getUserObject();
             if (userObject instanceof Directorio) {
            directorioPadre = (Directorio) userObject;
        } else {
            Archivo archivo = (Archivo) userObject;
            directorioPadre = archivo.getDirectorioPadre();
            selectedNode = (DefaultMutableTreeNode) selectedNode.getParent();
             }}
         
         //crear dir en el sistema
         if (sistemaArchivos.crearDirectorio(nombre, directorioPadre)) {
        // Crear el nodo visual para el nuevo directorio
        FileSystemElement nuevoElemento = directorioPadre.buscarElemento(nombre);
        DefaultMutableTreeNode nuevoNodo = new DefaultMutableTreeNode(nuevoElemento);

        // Insertar el nuevo nodo dentro del árbol visual
        treeModel.insertNodeInto(nuevoNodo, selectedNode, selectedNode.getChildCount());

        // Expandir para que se vea el nuevo directorio
        jTree1.expandPath(new TreePath(selectedNode.getPath()));
        jTree1.scrollPathToVisible(new TreePath(nuevoNodo.getPath()));

        JOptionPane.showMessageDialog(this, "Directorio creado exitosamente");
        FileDirName.setText("");
    } else {
        JOptionPane.showMessageDialog(this, "Error al crear el directorio (sin permisos o duplicado)");
    }

           
    }//GEN-LAST:event_CreateDirActionPerformed

    private void FileDirNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileDirNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FileDirNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainWindow().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateDir;
    private javax.swing.JButton CreateFile;
    private javax.swing.JTextField FileDirName;
    private javax.swing.JRadioButton IsAdmin;
    private javax.swing.JRadioButton isAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}